# templates configuration file (TOML)

output_file = "example/templates.go"

# no_cache = false
# no_go_format = false

template_base_dir = "tmpl"

package_name = "main"

# Asset manager to use
# - none (default)
# - go-bindata
asset_manager = "Go-Bindata"


# page_enum_type = "PageEnum"
# page_enum_prefix = "Page"
# page_enum_suffix = ""

# Name of the variable used as funcMap.
# The variable must be defined in another file of the same package (es. "templates/func-map.go")
# If not defined or blank, no funcMap will be used
func_map = "funcMap"

[templates]
flat = ["flat/footer.tmpl", "flat/header.tmpl", "flat/page1.tmpl", "flat/page2and3.tmpl"]
inhbase = ["inheritance/base.tmpl"]
inh1 = ["inhbase", "inheritance/content1.tmpl"]
inh2 = ["inhbase", "inheritance/content2.tmpl"]

[pages]
Pag1 = {template="flat", base="page-1"}
Pag2 = {template="flat", base="page-2"}
Pag3 = {template="flat", base="page-3"}
Inh1 = {template="inh1"}
Inh2 = {template="inh2"}

